###Get contract by id
GET http://localhost:3001/contracts/1
profile_id: 1

###Get contract by id (wrong profile)
GET http://localhost:3001/contracts/1
profile_id: 2

###Get all non terminated contracts belonging to profile
GET http://localhost:3001/contracts
profile_id: 1

###Get all unpaid jobs belonging to profile
GET http://localhost:3001/jobs/unpaid
profile_id: 1
